language: c++

cache: apt

dist: bionic

sudo: required

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;

      sudo apt-get install -qq build-essential;
      sudo apt-get install -qq cmake;
      sudo apt-get install -qq g++-8;
      sudo apt-get install -qq libssl-dev;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;

      brew install libuv;
    fi

script:
  - mkdir build && cd build

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake .. ;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 .. ;
    fi

  - make
